server:
  port: 0
management:
  endpoints:
    wed:
      exposure:
        include: "*"
spring:
  application:
    name: order
  zipkin:
    anabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: giang2211
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update

  cloud:
    loadbalancer:
      ribbon.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/microservices-realm


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


