
server:
  port: 8183
management:
  endpoints:
    wed:
      exposure:
        include: "*"
spring:
  application:
    name: inventory
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: giang2211
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
    defer-datasource-initialization: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/microservices-realm



eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

